baseURL = "/"
languageCode = "en-GB"
title = "CPressland.io"
theme = "terminal"

[params]
  themeColor = "pink"
  showMenuItems = 2
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = false

